apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-golang
  labels:
    app: kafka-consumer-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-golang
  template:
    metadata:
      labels:
        app: kafka-consumer-golang
    spec:
      containers:
      - name: kafka-consumer-golang
        image: banders2/kafka-consumer-golang:latest
        ports:
        - containerPort: 80