apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  ports:
  - port: 80
    name: broker
  clusterIP: None
  selector:
    app: broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
spec:
  serviceName: "broker"
  replicas: 3
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: banders2/broker
        ports:
        - containerPort: 80
          name: broker
---
apiVersion: v1
kind: Service
metadata:
  name: broker-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: broker-0
  ports:
  - protocol: TCP
    port: 81
    targetPort: 80